--Crear tabla TipoDp
CREATE TABLE TIPODP(
    CODTIPO NUMBER(4),
    DESCRIPCION VARCHAR2(50),
    CONSTRAINT PK_TIPODP PRIMARY KEY (CODTIPO)
);

--Añadir fk en DatosPersonales de la tabla TIPODP.
ALTER TABLE DATOSPERSONALES ADD CONSTRAINT FK_DATOSPERSONALES_TIPODP FOREIGN KEY (TIPO) REFERENCES TIPODP(CODTIPO);

--Se añade el campo anios a la tabla Director
ALTER TABLE DIRECTOR ADD ANIOS NUMBER(2);

--Eliminar campo comision de la tabla comercial
ALTER TABLE COMERCIAL DROP COLUMN COMISION;

--Tabla oficina, nuevo campo comision.
ALTER TABLE OFICINA ADD COMISION NUMBER(4);

--Nueva tabla TURNO con sus campos.
CREATE TABLE TURNO(
    CODTURNO NUMBER(4),
    DESCRIPCION VARCHAR2(50),
    CONSTRAINT PK_TURNO PRIMARY KEY (CODTURNO)
);
--En la tabla vendedor, TURNO pasa a ser una fk de TURNO.
ALTER TABLE VENDEDOR ADD CONSTRAINT FK_VENDEDOR_TURNO FOREIGN KEY (TURNO) REFERENCES TURNO(CODTURNO);

--Crear tabla TEMATICA con sus campos
CREATE TABLE TEMATICA(
    CODTEM NUMBER(4),
    DESCRIPCION VARCHAR2(50),
    CONSTRAINT PK_TEMATICA PRIMARY KEY (CODTEM)
);
--Tabla libro, renombrar campo preciO a precioactual, TEMATICA pasa a ser una fk de tematica 
ALTER TABLE LIBRO RENAME COLUMN PRECIO TO PRECIOALTUAL;