CREATE TABLE SEDE(
CODSEDE NUMBER(2) NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
DIRECCION VARCHAR(30) NOT NULL,
CONSTRAINT PK_SEDE PRIMARY KEY(CODSEDE)
);

CREATE TABLE DEPARTARMENTO(
CODDEP NUMBER(2) NOT NULL,
CODSEDE NUMBER(2) NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
DIRECCION VARCHAR(30) NOT NULL,
CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(CODDEP,CODSEDE),
CONSTRAINT FK_DEPSEDE FOREIGN KEY(CODSEDE) REFERENCES SEDE(CODSEDE) ON DELETE CASCADE
);

CREATE TABLE PROGRAMADOR(
SECUENCIA NUMBER(3) NOT NULL,
PROGMENTOR NUMBER(3) NOT NULL,
CODDEP NUMBER(2) NOT NULL,
CODSEDE NUMBER(2) NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
AP1 VARCHAR(30) NOT NULL,
AP2 VARCHAR(3) NULL,
DIRECCION VARCHAR(30) NOT NULL,
CUENTA VARCHAR(30) NOT NULL,
TELEFONO NUMBER(9) NOT NULL,
TIPO VARCHAR(30) NOT NULL,
CONSTRAINT PK_PROGRAMADOR PRIMARY KEY (SECUENCIA,CODDEP,CODSEDE),
CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY (CODDEP,CODSEDE) REFERENCES DEPARTARMENTO(CODDEP,CODSEDE) ON DELETE CASCADE,
CONSTRAINT FK_PROGMENTOR FOREIGN KEY (PROGMENTOR,CODDEP,CODSEDE) REFERENCES PROGRAMADOR(SECUENCIA,CODDEP,CODSEDE) ON DELETE CASCADE
);

CREATE TABLE EQUIPO(
CODEQUIPO NUMBER(2) NOT NULL,
SECUENCIA NUMBER(3) NOT NULL,
CODDEP NUMBER(2) NOT NULL,
CODSEDE NUMBER(2) NOT NULL,
DESCRIPCION VARCHAR(30) NOT NULL,
CONSTRAINT PK_EQUIPO PRIMARY KEY(CODEQUIPO),
CONSTRAINT FK_PROG FOREIGN KEY (SECUENCIA,CODDEP,CODSEDE) REFERENCES PROGRAMADOR(SECUENCIA,CODDEP,CODSEDE) ON DELETE CASCADE
);

CREATE TABLE EQUIPOPROG(
SECUENCIA NUMBER(3) NOT NULL,
CODDEP NUMBER(2) NOT NULL,
CODSEDE NUMBER(2) NOT NULL,
CODEQUIPO NUMBER(2) NOT NULL,
CONSTRAINT PK_EQUIPOPROG PRIMARY KEY(SECUENCIA,CODDEP,CODSEDE,CODEQUIPO)
);

CREATE TABLE PROYECTO(
FECHAINI DATE NOT NULL,
DESCRIPCION VARCHAR(30) NOT NULL,
FECHAFIN DATE NULL,
CODEQUIPO NUMBER(2) NOT NULL,
SUBPROYECTO DATE NOT NULL,
CONSTRAINT PK_PROYECTO PRIMARY KEY(FECHAINI,CODEQUIPO),
CONSTRAINT FK_EQUIPO FOREIGN KEY (CODEQUIPO) REFERENCES EQUIPO(CODEQUIPO) ON DELETE CASCADE,
CONSTRAINT FK_SUBPROYECTO FOREIGN KEY(SUBPROYECTO,CODEQUIPO) REFERENCES PROYECTO(FECHAINI,CODEQUIPO) ON DELETE CASCADE
);
