CREATE TABLE DATOSPERSONALES (
    DNI VARCHAR2 (9),
    NOMBRE VARCHAR2 (30),
    APE1 VARCHAR2 (50),
    APE2 VARCHAR2 (50) NULL,
    DIRECCION VARCHAR2 (70),
    TELEFONO NUMBER (12),
    TIPO VARCHAR2 (8),
    CONSTRAINT pk_datosPersonales PRIMARY KEY (DNI),
    CONSTRAINT ck_datosPersonales CHECK (TIPO IN ('ALUMNO', 'PROFESOR')),
);

ALTER TABLE PROFESOR DROP COLUMN NOMBRE;
ALTER TABLE PROFESOR DROP COLUMN APE1;
ALTER TABLE PROFESOR DROP COLUMN APE2;
ALTER TABLE PROFESOR DROP COLUMN DIRECCION;
ALTER TABLE PROFESOR DROP COLUMN TELEFONO;

ALTER TABLE ALUMNO DROP COLUMN NOMBRE;
ALTER TABLE ALUMNO DROP COLUMN APE1;
ALTER TABLE ALUMNO DROP COLUMN APE2;
ALTER TABLE ALUMNO DROP COLUMN DIRECCION;
ALTER TABLE ALUMNO DROP COLUMN TELEFONO;

ALTER TABLE PROFESOR ADD CONSTRAINT fk_profesor_datosPersonales FOREIGN KEY (DNI) REFERENCES DATOSPERSONALES (DNI);
ALTER TABLE ALUMNO ADD CONSTRAINT fk_alumno_datosPersonales FOREIGN KEY (DNI) REFERENCES DATOSPERSONALES (DNI);
