<<<<<<< HEAD
CREATE TABLE CLIENTE4_2(
=======
CREATE TABLE CLIENTE(
>>>>>>> 8db0f0c800b544781cc02ecc5ebeb320aec7d887
    NOMBRE VARCHAR2(20),
    APELLIDO1 VARCHAR2(30),
    APELLIDO2 VARCHAR2(30) NULL,
    DOMICILIO VARCHAR2(40),
    NUMTARJETA NUMBER(9),
    DNICLIENTE VARCHAR2(9),
<<<<<<< HEAD
    CONSTRAINT pk_cliente4_2 PRIMARY KEY (DNICLIENTE)
);

CREATE TABLE FABRICANTE4_2(
    FABRICANTE VARCHAR2(20),
    CODFABRICANTE VARCHAR2(20),
    CONSTRAINT pk_fabricante4_2 PRIMARY KEY (CODFABRICANTE)
);

CREATE TABLE MARCA4_2(
    MARCA VARCHAR2(20),
    CODMARCA VARCHAR2(20),
    CONSTRAINT pk_marca4_2 PRIMARY KEY (CODMARCA)
);

CREATE TABLE VEHICULO4_2(
=======
    CONSTRAINT pk_cliente PRIMARY KEY (DNICLIENTE)
);

CREATE TABLE FABRICANTE(
    FABRICANTE VARCHAR2(20),
    CODFABRICANTE VARCHAR2(20),
    CONSTRAINT pk_fabricante PRIMARY KEY (CODFABRICANTE)
);

CREATE TABLE MARCA(
    MARCA VARCHAR2(20),
    CODMARCA VARCHAR2(20),
    CONSTRAINT pk_marca PRIMARY KEY (CODMARCA)
);

CREATE TABLE VEHICULO(
>>>>>>> 8db0f0c800b544781cc02ecc5ebeb320aec7d887
    MODELO VARCHAR2(30),
    TIPO VARCHAR2(20),
    COLOR VARCHAR2(15),
    CODFABRICANTE VARCHAR2(20),
    CODMARCA VARCHAR2(20),
    CODVEHICULO VARCHAR2 (20),
<<<<<<< HEAD
    CONSTRAINT pk_vehiculo4_2 PRIMARY KEY (CODVEHICULO),
    CONSTRAINT fk_fabricante4_2 FOREIGN KEY (CODFABRICANTE) REFERENCES FABRICANTE4_2 (CODFABRICANTE),
    CONSTRAINT fk_marca4_2 FOREIGN KEY (CODMARCA) REFERENCES MARCA4_2 (CODMARCA)
);

CREATE TABLE CURSO4_2(
=======
    CONSTRAINT pk_vehiculo PRIMARY KEY (CODVEHICULO),
    CONSTRAINT fk_fabricante FOREIGN KEY (CODFABRICANTE) REFERENCES FABRICANTE (CODFABRICANTE),
    CONSTRAINT fk_marca FOREIGN KEY (CODMARCA) REFERENCES MARCA (CODMARCA)
);

CREATE TABLE CURSO(
>>>>>>> 8db0f0c800b544781cc02ecc5ebeb320aec7d887
    DESCRIPCION VARCHAR2(50),
    NUMHORAS NUMBER(3),
    FECHA DATE,
    CODCURSO VARCHAR2(20),
<<<<<<< HEAD
    CONSTRAINT pk_curso4_2 PRIMARY KEY (CODCURSO)
);

CREATE TABLE EMPLEADO4_2(
=======
    CONSTRAINT pk_curso PRIMARY KEY (CODCURSO)
);

CREATE TABLE EMPLEADO(
>>>>>>> 8db0f0c800b544781cc02ecc5ebeb320aec7d887
    NOMBRE VARCHAR2(20),
    APELLIDO1 VARCHAR(30),
    APELLIDO2 VARCHAR2(30) NULL,
    DOMICILIO VARCHAR2(40),
    NUMCUENTA VARCHAR2(20),
    DNIEMPLEADO VARCHAR2(9),
<<<<<<< HEAD
    CONSTRAINT pk_empleado4_2 PRIMARY KEY (DNIEMPLEADO)
);

CREATE TABLE CURSOEMPLEADO4_2(
    DNIEMPLEADO VARCHAR2(9),
    CODCURSO VARCHAR2(20),
    CONSTRAINT pk_cursoempleado4_2 PRIMARY KEY (DNIEMPLEADO, CODCURSO),
    CONSTRAINT fk_empleado4_2 FOREIGN KEY (DNIEMPLEADO) REFERENCES EMPLEADO4_2 (DNIEMPLEADO),
    CONSTRAINT fk_curso4_2 FOREIGN KEY (CODCURSO) REFERENCES CURSO4_2 (CODCURSO)
);

CREATE TABLE OFICINA4_2(
=======
    CONSTRAINT pk_empleado PRIMARY KEY (DNIEMPLEADO)
);

CREATE TABLE CURSOEMPLEADO(
    DNIEMPLEADO VARCHAR2(9),
    CODCURSO VARCHAR2(20),
    CONSTRAINT pk_cursoempleado PRIMARY KEY (DNIEMPLEADO, CODCURSO),
    CONSTRAINT fk_empleado FOREIGN KEY (DNIEMPLEADO) REFERENCES EMPLEADO (DNIEMPLEADO),
    CONSTRAINT fk_curso FOREIGN KEY (CODCURSO) REFERENCES CURSO (CODCURSO)
);

CREATE TABLE OFICINA(
>>>>>>> 8db0f0c800b544781cc02ecc5ebeb320aec7d887
    DOMICILIO VARCHAR2(40),
    TELEFONO NUMBER(9),
    CODOFICINALLEGADA VARCHAR2(20),
    CODOFICINASALIDA VARCHAR2(20),
<<<<<<< HEAD
    CONSTRAINT pk_oficina4_2 PRIMARY KEY (CODOFICINALLEGADA, CODOFICINASALIDA)
);

CREATE TABLE ALQUILER4_2(
=======
    CONSTRAINT pk_oficina PRIMARY KEY (CODOFICINALLEGADA, CODOFICINASALIDA)
);

CREATE TABLE ALQUILER(
>>>>>>> 8db0f0c800b544781cc02ecc5ebeb320aec7d887
    FECHA DATE,
    NUMDIAS NUMBER(3),
    KMACTUAL VARCHAR2(10),
    KMENTREGA VARCHAR2(10),
    CODALQUILER VARCHAR2(20),
    DNICLIENTE VARCHAR2(9) NULL,
    DNIEMPLEADO VARCHAR2(9),
    CODVEHICULO VARCHAR2(20) NULL,
<<<<<<< HEAD
    CONSTRAINT pk_alquiler4_2 PRIMARY KEY (CODALQUILER),
    CONSTRAINT fk_empleadoalquiler4_2 FOREIGN KEY (DNIEMPLEADO) REFERENCES EMPLEADO4_2 (DNIEMPLEADO),
    CONSTRAINT fk_clientealquiler4_2 FOREIGN KEY (DNICLIENTE) REFERENCES CLIENTE4_2 (DNICLIENTE),
    CONSTRAINT fk_vehiculoalquiler4_2 FOREIGN KEY (CODVEHICULO) REFERENCES VEHICULO4_2 (CODVEHICULO)
);

CREATE TABLE OFICINASALQUILER4_2(
    CODOFICINASALIDA VARCHAR2(20),
    CODOFICINALLEGADA VARCHAR2(20),
    CODALQUILER VARCHAR2(20),
    CONSTRAINT pk_oficinaslalquiler4_2 PRIMARY KEY (CODOFICINASALIDA, CODOFICINALLEGADA, CODALQUILER),
    CONSTRAINT fk_oficinasalquiler4_2 FOREIGN KEY (CODOFICINASALIDA, CODOFICINALLEGADA) REFERENCES OFICINA4_2 (CODOFICINALLEGADA, CODOFICINASALIDA),
    CONSTRAINT fk_alquileroficinasalquiler4_2 FOREIGN KEY (CODALQUILER) REFERENCES ALQUILER4_2 (CODALQUILER)
=======
    CONSTRAINT pk_alquiler PRIMARY KEY (CODALQUILER),
    CONSTRAINT fk_empleadoalquiler FOREIGN KEY (DNIEMPLEADO) REFERENCES EMPLEADO (DNIEMPLEADO),
    CONSTRAINT fk_clientealquiler FOREIGN KEY (DNICLIENTE) REFERENCES CLIENTE (DNICLIENTE),
    CONSTRAINT fk_vehiculoalquiler FOREIGN KEY (CODVEHICULO) REFERENCES VEHICULO (CODVEHICULO)
);

CREATE TABLE OFICINASALQUILER(
    CODOFICINASALIDA VARCHAR2(20),
    CODOFICINALLEGADA VARCHAR2(20),
    CODALQUILER VARCHAR2(20),
    CONSTRAINT pk_oficinaslalquiler PRIMARY KEY (CODOFICINASALIDA, CODOFICINALLEGADA, CODALQUILER),
    CONSTRAINT fk_oficinasalquiler FOREIGN KEY (CODOFICINASALIDA, CODOFICINALLEGADA) REFERENCES OFICINA (CODOFICINALLEGADA, CODOFICINASALIDA),
    CONSTRAINT fk_alquileroficinasalquiler FOREIGN KEY (CODALQUILER) REFERENCES ALQUILER (CODALQUILER)
>>>>>>> 8db0f0c800b544781cc02ecc5ebeb320aec7d887
);