CREATE TABLE CLIENTE4_2(
    NOMBRE VARCHAR2(20),
    APELLIDO1 VARCHAR2(30),
    APELLIDO2 VARCHAR2(30) NULL,
    DOMICILIO VARCHAR2(40),
    NUMTARJETA NUMBER(9),
    DNICLIENTE VARCHAR2(9),
    CONSTRAINT pk_cliente4_2 PRIMARY KEY (DNICLIENTE)
);

CREATE TABLE FABRICANTE4_2(
    FABRICANTE VARCHAR2(20),
    CODFABRICANTE VARCHAR2(20),
    CONSTRAINT pk_fabricante4_2 PRIMARY KEY (CODFABRICANTE)
);

CREATE TABLE MARCA4_2(
    MARCA VARCHAR2(20),
    CODMARCA VARCHAR2(20),
    CONSTRAINT pk_marca4_2 PRIMARY KEY (CODMARCA)
);

CREATE TABLE VEHICULO4_2(
    MODELO VARCHAR2(30),
    TIPO VARCHAR2(20),
    COLOR VARCHAR2(15),
    CODFABRICANTE VARCHAR2(20),
    CODMARCA VARCHAR2(20),
    CODVEHICULO VARCHAR2 (20),
    CONSTRAINT pk_vehiculo4_2 PRIMARY KEY (CODVEHICULO),
    CONSTRAINT fk_fabricante4_2 FOREIGN KEY (CODFABRICANTE) REFERENCES FABRICANTE4_2 (CODFABRICANTE),
    CONSTRAINT fk_marca4_2 FOREIGN KEY (CODMARCA) REFERENCES MARCA4_2 (CODMARCA)
);

CREATE TABLE CURSO4_2(
    DESCRIPCION VARCHAR2(50),
    NUMHORAS NUMBER(3),
    FECHA DATE,
    CODCURSO VARCHAR2(20),
    CONSTRAINT pk_curso4_2 PRIMARY KEY (CODCURSO)
);

CREATE TABLE EMPLEADO4_2(
    NOMBRE VARCHAR2(20),
    APELLIDO1 VARCHAR(30),
    APELLIDO2 VARCHAR2(30) NULL,
    DOMICILIO VARCHAR2(40),
    NUMCUENTA VARCHAR2(20),
    DNIEMPLEADO VARCHAR2(9),
    CONSTRAINT pk_empleado4_2 PRIMARY KEY (DNIEMPLEADO)
);

CREATE TABLE CURSOEMPLEADO4_2(
    DNIEMPLEADO VARCHAR2(9),
    CODCURSO VARCHAR2(20),
    CONSTRAINT pk_cursoempleado4_2 PRIMARY KEY (DNIEMPLEADO, CODCURSO),
    CONSTRAINT fk_empleado4_2 FOREIGN KEY (DNIEMPLEADO) REFERENCES EMPLEADO4_2 (DNIEMPLEADO),
    CONSTRAINT fk_curso4_2 FOREIGN KEY (CODCURSO) REFERENCES CURSO4_2 (CODCURSO)
);

CREATE TABLE OFICINA4_2(
    DOMICILIO VARCHAR2(40),
    TELEFONO NUMBER(9),
    CODOFICINALLEGADA VARCHAR2(20),
    CODOFICINASALIDA VARCHAR2(20),
    CONSTRAINT pk_oficina4_2 PRIMARY KEY (CODOFICINALLEGADA, CODOFICINASALIDA)
);

CREATE TABLE ALQUILER4_2(
    FECHA DATE,
    NUMDIAS NUMBER(3),
    KMACTUAL VARCHAR2(10),
    KMENTREGA VARCHAR2(10),
    CODALQUILER VARCHAR2(20),
    DNICLIENTE VARCHAR2(9) NULL,
    DNIEMPLEADO VARCHAR2(9),
    CODVEHICULO VARCHAR2(20) NULL,
    CONSTRAINT pk_alquiler4_2 PRIMARY KEY (CODALQUILER),
    CONSTRAINT fk_empleadoalquiler4_2 FOREIGN KEY (DNIEMPLEADO) REFERENCES EMPLEADO4_2 (DNIEMPLEADO),
    CONSTRAINT fk_clientealquiler4_2 FOREIGN KEY (DNICLIENTE) REFERENCES CLIENTE4_2 (DNICLIENTE),
    CONSTRAINT fk_vehiculoalquiler4_2 FOREIGN KEY (CODVEHICULO) REFERENCES VEHICULO4_2 (CODVEHICULO)
);

CREATE TABLE OFICINASALQUILER4_2(
    CODOFICINASALIDA VARCHAR2(20),
    CODOFICINALLEGADA VARCHAR2(20),
    CODALQUILER VARCHAR2(20),
    CONSTRAINT pk_oficinaslalquiler4_2 PRIMARY KEY (CODOFICINASALIDA, CODOFICINALLEGADA, CODALQUILER),
    CONSTRAINT fk_oficinasalquiler4_2 FOREIGN KEY (CODOFICINASALIDA, CODOFICINALLEGADA) REFERENCES OFICINA4_2 (CODOFICINALLEGADA, CODOFICINASALIDA),
    CONSTRAINT fk_alquileroficinasalquiler4_2 FOREIGN KEY (CODALQUILER) REFERENCES ALQUILER4_2 (CODALQUILER)
);