CREATE TABLE PROFESOR3_1 (
    DNI VARCHAR2 (9),
    NOMBRE VARCHAR2 (30),
    APELLIDO1 VARCHAR2 (30),
    APELLIDO2 VARCHAR2 (30) NULL,
    DIRECCION VARCHAR2 (50), 
    CUENTA VARCHAR2 (26),
    TELEFONO NUMBER (9),
    CONSTRAINT pk_profesor3_1 PRIMARY KEY (DNI)
);

CREATE TABLE CICLO_FORMATIVO3_1 (
    CODCICLO NUMBER (20) NOT NULL,
    NOMBRE VARCHAR2 (20) NOT NULL,
    TIPO VARCHAR2 (20) NOT NULL,
    CONSTRAINT pk_cicloformativo3_1 PRIMARY KEY (CODCICLO)
);

CREATE TABLE ASIGNATURA3_1 (
    CODASIG VARCHAR2 (20) NOT NULL,
    NOMBRE VARCHAR2 (20) NOT NULL,
    NUM_HORAS NUMBER (3) NOT NULL,
    CODCICLO NUMBER (20) NOT NULL,
    DNI VARCHAR2 (9),
    CONSTRAINT pk_asignatura2 PRIMARY KEY(CODASIG),
    CONSTRAINT fk_ciclo3_1 FOREIGN KEY (CODCICLO) REFERENCES CICLO_FORMATIVO3_1 (CODCICLO),
    CONSTRAINT fk_prof3_1 FOREIGN KEY (DNI) REFERENCES PROFESOR3_1 (DNI)
);

CREATE TABLE IDIOMA3_1 (
    CODIDIOMA VARCHAR2 (20) NOT NULL,
    DESCRIPCION VARCHAR2 (50) NOT NULL,
    CONSTRAINT pk_codidioma3_1 PRIMARY KEY (CODIDIOMA)
);

CREATE TABLE IDIOMA_PROFESOR3_1 (
    CODIDIOMA VARCHAR2 (20) NOT NULL,
    DNI VARCHAR2 (9),
    CONSTRAINT pk_idiomaprofe PRIMARY KEY (CODIDIOMA, DNI),
    CONSTRAINT fk_idioma FOREIGN KEY (CODIDIOMA) REFERENCES IDIOMA3_1 (CODIDIOMA),
    CONSTRAINT fk_profesor FOREIGN KEY (DNI) REFERENCES PROFESOR3_1 (DNI)
);

CREATE TABLE ALUMNO3_1 (
    DNI_ALUMNO VARCHAR2 (9),
    NOMBRE VARCHAR2 (30),
    APELLIDO1 VARCHAR2 (30),
    APELLIDO2 VARCHAR2 (30) NULL,
    DIRECCION VARCHAR2 (50),
    EMAIL VARCHAR2 (30),
    TELEFONO NUMBER (9),
    CODIDIOMA VARCHAR2 (20) NOT NULL,
    CONSTRAINT pk_alumno PRIMARY KEY (DNI_ALUMNO),
    CONSTRAINT fk_idioma2 FOREIGN KEY (CODIDIOMA) REFERENCES IDIOMA3_1 (CODIDIOMA) 
);

CREATE TABLE MATRICULA3_1 (
    DNI_ALUMNO VARCHAR2 (9),
    CODASIG VARCHAR2 (20) NOT NULL,
    CONSTRAINT pk_matricula PRIMARY KEY (CODASIG, DNI_ALUMNO),
    CONSTRAINT fk_asig FOREIGN KEY (CODASIG) REFERENCES ASIGNATURA3_1 (CODASIG),
    CONSTRAINT fk_alumno FOREIGN KEY (DNI_ALUMNO) REFERENCES ALUMNO3_1 (DNI_ALUMNO)
);