CREATE TABLE AULA (
    ID_AULA NUMER(3),
    TIPO_AULA VARCHAR(20),
    CONSTRAINT pk_id_aula PRIMARY KEY (ID_AULA)
)

ALTER TABLE DOCTORANDO_CURSO DROP CONSTRAINT pk_DoctorandoCurso

ALTER TABLE DOCTORANDO_CURSO ADD CONSTRAINT pk_DoctorandoCurso PRIMARY KEY (ID_DOCTORANDO, ID_CURSO, FECHA_COMIENZO),


CREATE TABLE CURSO_AULA (
    ID_CURSO NUMBER(3),
    ID_AULA NUMBER(3),
    CONSTRAINT pk_curso_aula PRIMARY KEY (ID_CURSO, ID_AULA),
    CONSTRAINT fk_curso_aula FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO),
    CONSTRAINT fk_aula_curso FOREIGN KEY (ID_AULA) REFERENCES AULA(ID_AULA),
)


INSERT INTO AULA VALUES ('PRACTICAS', 'AUDIOVISUAL', 'GRUPOS_PEQUEÑOS', 'NORMAL', 'MAGNA');