CREATE TABLE OFICINA(
	CODOFICINA NUMBER (9),
	DIRECCION VARCHAR2 (40),
	DNIDIR VARCHAR2 (9),
	DNICOM VARCHAR2 (9),
	CONSTRAINT pk_oficina PRIMARY KEY (CODOFICINA),
	CONSTRAINT fk_director FOREING KEY (DNIDIR) REFERENCES DIRECTOR (DNI),
	CONSTRAINT fk_comercial FOREING KEY (DNICOM) REFERENCES COMERCIAL (DNI),
	CONSTRAINT ck_oficina CHECK (DNIDIR = 1),
	CONSTRAINT ck_oficina CHECK (DNICOM > 1)
);

CREATE TABLE VENDEDOR(
	DNI VARCHAR2 (9),
	TURNO CHAR (1),
	CODOFICINA NUMBER (9),
	CONSTRAINT pk_vendedor PRIMARY KEY (DNI) ON DELETE CASCADE,
	CONSTRAINT fk_datospersonalesvend FOREING KEY (DNI) REFERENCES DATOSPERSONALES (DNI),
	CONSTRAINT fk_oficinavend FOREING KEY (CODOFICINA) REFERENCES OFICINA (CODOFICINA),
	CONSTRAINT ck_vendtur CHECK (TURNO IN ('M', 'T')
);

CREATE TABLE COMERCIAL(
	DNI VARCHAR2 (9),
	COMISION VARCHAR2 (4),
	CODOFICINA NUMBER (9),
	CONSTRAINT pk_comercial PRIMARY KEY (DNI),
	CONSTRAINT fk_datospersonalescom FOREING KEY (DNI) REFERENCES DATOSPERSONALES (DNI),
	CONSTRAINT fk_oficinacom FOREING KEY (CODOFICINA) REFERENCES OFICINA (CODOFICINA),
);