--! a) DIRECTOR 
ALTER TABLE Director ADD CONSTRAINT pk_director PRIMARY KEY (Dni);

ALTER TABLE DIRECTOR MODIFY Nombre VARCHAR2(30) NOT NULL;
ALTER TABLE DIRECTOR MODIFY AP1 VARCHAR2(30) NOT NULL;
ALTER TABLE DIRECTOR MODIFY DOMICILIO VARCHAR2(30) NOT NULL;
ALTER TABLE DIRECTOR MODIFY TELEFONO VARCHAR2(30) NOT NULL;

--! b)
--! CHEK Supermercado
ALTER TABLE Supermercado MODIFY esAlquiler CHAR(1)  NOT NULL;

ALTER TABLE Supermercado MODIFY Fecha DATE NOT NULL;

ALTER TABLE Supermercado ADD CONSTRAINT ck_superficie CHECK (Superficie >= 0);
ALTER TABLE Supermercado ADD CONSTRAINT ck_esAlquiler CHECK (esAlquiler IN('s','S','N','n'));

ALTER TABLE Supermercado ADD CONSTRAINT fk_DNIdirec FOREIGN KEY (Dni) REFERENCES Director(Dni);

--! c) VENDEDOR ON DELETE CASCADE
ALTER TABLE Vendedor ADD CONSTRAINT fk_refSUPER FOREIGN KEY (refSUPER) REFERENCES Supermercado (CodSup) ON DELETE CASCADE;

--! d) CLIENTE 
ALTER TABLE Cliente MODIFY Dni PRIMARY KEY;

ALTER TABLE Cliente MODIFY AP2 VARCHAR2(30) NULL,
ALTER TABLE Cliente MODIFY email VARCHAR2 (40) NULL,

--! e) FKS ON DELETE CASCADE 
ALTER TABLE Vendedor ADD CONSTRAINT fk_refVENDEDOR FOREIGN KEY (refVENDEDOR) REFERENCES VENDEDOR (DNI) ON DELETE CASCADE;
ALTER TABLE Vendedor ADD CONSTRAINT fk_refCLIENTE FOREIGN KEY (refCLIENTE) REFERENCES CLIENTE (DNI) ON DELETE CASCADE;

--! f) PRODUCTO CHEK descuento e iva
ALTER TABLE Producto MODIFY Descuento NUMBER (3) DEFAULT 0;
ALTER TABLE Producto ADD CONSTRAINT ck_precio CHECK (Descuento BETWEEN 0 AND 100); --! (Descuento (0-100)

ALTER TABLE Producto ADD CONSTRAINT ck_iva CHECK (IVA IN (4, 10, 21));

--! g) Linea venta
ALTER TABLE LINEAVENTA ADD CONSTRAINT ck_cantidad CHECK (TipoDev BETWEEN 1 AND 249); --! hasta 250

--! h) DEVOLUCION
ALTER TABLE Devolucion ADD CONSTRAINT ck_estado CHECK (Estado IN ('B', 'M', 'F'));
ALTER TABLE Devolucion ADD CONSTRAINT ck_tipodev CHECK (TipoDev BETWEEN 1 AND 5); --! (TipoDev (1-5))


--! i) 
ALTER TABLE Precio MODIFY Descuento NUMBER (6,2);
ALTER TABLE Precio ADD CONSTRAINT ck_precio CHECK (Precio BETWEEN 0.01 AND 9999.99); --! Number (6)