CREATE TABLE AUTOBUS (
    MATRICULA VARCHAR2(7),
    ANTIGUEDAD NUMBER(2),
    FECHAITV  DATE,
    NUMEROPLAZAS NUMBER(3),
    
    CONSTRAINT pk_autobus PRIMARY KEY (MATRICULA),
    CONSTRAINT ck_autobus CHECK ( NUMEROPLAZAS <=100)
);

ALTER TABLE  AUTOBUS modify MATRICULA VARCHAR(7) NOT NULL;
ALTER TABLE  AUTOBUS modify ANTIGUEDAD NUMBER(2) NOT NULL;
ALTER TABLE  AUTOBUS modify FECHAITV DATE NOT NULL;
ALTER TABLE  AUTOBUS modify NUMEROPLAZAS NUMBER(3) NOT NULL;


CREATE TABLE CONDUCTOR (
    DNI VARCHAR(9),
    NOMBRE CHAR(30),
    APELLIDO1 CHAR(30),
    APELLIDO2 CHAR(30) NULL ,
    NUMEROEMPLEADO NUMBER(6), 
    
    CONSTRAINT pk_conductor PRIMARY KEY (DNI)
);

CREATE TABLE VIAJES (
    DNICONDUCTOR VARCHAR(9), 
    MATRICULAAUTOBUS VARCHAR(7),
    DESTINO CHAR(40),
    FECHA NUMBER (8),
    DNI VARCHAR(9),
    MATRICULA VARCHAR2(7),
    
    CONSTRAINT pk_viajes PRIMARY KEY (DNICONDUCTOR , MATRICULAAUTOBUS , FECHA) ,
    CONSTRAINT fk_conductor FOREIGN KEY ( DNICONDUCTOR) references CONDUCTOR (DNI) on delete cascade ,
    CONSTRAINT fk_autobus  FOREIGN KEY ( MATRICULA) references autobus (MATRICULA) on delete cascade 
);  
    
    


    
    
