                                                        -- SUBCONSULTAS CON IN Y NOT IN --

-- 11.SUBCONSULTA CON IN Y NOT IN -- DEVUELVE NOMBRES FAB QUE TIENE PRODUCTOS ASOCIADOS
SELECT NOMBRE FROM FABRICANTES WHERE id IN (SELECT id_fabricante FROM PRODUCTOS);
-- 12.SUBCONSULTA CON IN Y NOT IN -- DEVUELVE NOMBRES FAB QUE NO TIENE PRODUCTOS ASOCIADOS
SELECT NOMBRE FROM FABRICANTES WHERE id NOT IN (SELECT id_fabricante FROM PRODUCTOS);

                                                        -- SUBCONSULTAS CON EXITS Y NOT EXISTS --
                                                      
-- 13.SUBCONSULTAS CON EXITS Y NOT EXISTS -- DEVUELVE NOMBRES FAB QUE TIENE PRODUCTOS ASOCIADOS
SELECT NOMBRE FROM FABRICANTES F WHERE EXISTS (SELECT * FROM PRODUCTOS P WHERE F.ID = P.ID_FABRICANTE);
-- 14.SUBCONSULTAS CON EXITS Y NOT EXISTS -- DEVUELVE NOMBRES FAB QUE NO TIENE PRODUCTOS ASOCIADOS
SELECT NOMBRE FROM FABRICANTES F WHERE NOT EXISTS (SELECT * FROM PRODUCTOS P WHERE F.ID = P.ID_FABRICANTE);

                                                        -- SUBCONSULTAS CORRELACIONADAS --

-- 15.SUBCONSULTAS CORRELACIONADAS -- LISTA NOMBRE FAB CON NOMBRE Y PRECIO PRODUCTO MAS CARO
SELECT F.NOMBRE AS FABRICANTE, P.NOMBRE AS PRODUCTO, P.PRECIO FROM FABRICANTES F, PRODUCTOS P WHERE F.ID = P.ID_FABRICANTE AND P.PRECIO = (SELECT MAX(PRECIO) FROM PRODUCTOS);
-- OTRA MANERA --
SELECT F.NOMBRE, MAX(P.PRECIO) FROM FABRICANTES F, PRODUCTOS P WHERE F.ID = P.ID_FABRICANTE GROUP BY F.NOMBRE;
-- 16.SUBCONSULTAS CORRELACIONADAS -- LISTADO DE TODOS LOS PRODUCTOS QUE TIENEN PRECIO MAYOR O IGUAL MEDIA PRODUCTOS MISMO FAB.
SELECT P.NOMBRE AS PRODUCTO, P.PRECIO FROM PRODUCTOS P WHERE P.PRECIO >= (SELECT AVG(PRECIO) FROM PRODUCTOS WHERE ID_FABRICANTE = P.ID_FABRICANTE);

-- 17.SUBCONSULTAS CORRELACIONADAS -- NOMBRE PRODUCTO MAS CARO DE FAB LENOVO.
SELECT P.NOMBRE AS PRODUCTO, P.PRECIO FROM PRODUCTOS P WHERE P.ID_FABRICANTE = (SELECT ID FROM FABRICANTES WHERE NOMBRE = 'Lenovo') AND P.PRECIO = (SELECT MAX(PRECIO) FROM PRODUCTOS WHERE ID_FABRICANTE = P.ID_FABRICANTE);

                                                        -- SUBCONSULTAS EN CLAUSULA HAVING --
                                                        
-- 18.SUBCONSULTA EN LA CLAUSULA HAVING.-- LISTA CON TODOS LOS NOMBRES DE LOS FABRICANTES QUE TIENEN MISMO NUMERO DE PRODUCTO QUE LENOVO.
SELECT F.NOMBRE 
FROM FABRICANTES F 
JOIN PRODUCTOS P ON F.ID = P.ID_FABRICANTE
GROUP BY F.NOMBRE
HAVING COUNT(P.ID) = (SELECT COUNT(*) FROM PRODUCTOS WHERE ID_FABRICANTE = (SELECT ID FROM FABRICANTES WHERE UPPER(NOMBRE) = UPPER('Lenovo')));