--SUBCONSULTAS ALL Y ANY
--SUB 7
SELECT * FROM PRODUCTOS P
WHERE P.PRECIO >= ALL(SELECT PRECIO FROM PRODUCTOS);

--SUB 8
SELECT * FROM PRODUCTOS P
WHERE P.PRECIO <= ALL(SELECT PRECIO FROM PRODUCTOS);

--SUB 9
SELECT F.NOMBRE FROM FABRICANTES F
WHERE F.ID = ANY(SELECT ID_FABRICANTE FROM PRODUCTOS);

--SUB 10
SELECT F.NOMBRE FROM FABRICANTES F
WHERE F.ID <> ALL(SELECT ID_FABRICANTE FROM PRODUCTOS);