--Parte de Alfonso
--Consultas multitabla (Composición externa)<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

--A
SELECT F.NOMBRE, P.NOMBRE
FROM FABRICANTES F
LEFT JOIN PRODUCTOS P
ON F.ID = P.ID_FABRICANTE;

--B
SELECT F.NOMBRE, P.NOMBRE
FROM FABRICANTES F
LEFT JOIN PRODUCTOS P
ON F.ID = P.ID_FABRICANTE
WHERE P.NOMBRE IS NULL;

--C
-- No puede ser, ya que un producto siempre debe tener un fabricante pero
-- un fabricante puede no tener productos.

--Consultas resumen<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

--1)
SELECT COUNT (*)
FROM PRODUCTOS;

--2)
SELECT COUNT (ID)
FROM PRODUCTOS;

--3)
SELECT AVG(P.PRECIO)
FROM PRODUCTOS P;

--4)
SELECT MIN(P.PRECIO)
FROM PRODUCTOS P;

--5)
SELECT P.NOMBRE, P.PRECIO
FROM PRODUCTOS P
WHERE P.PRECIO = (SELECT MAX(PRECIO) FROM PRODUCTOS);

--6)
SELECT SUM(P.PRECIO)
FROM PRODUCTOS P;

--7)
SELECT COUNT (*)
FROM PRODUCTOS P, FABRICANTES F
WHERE F.ID = P.ID_FABRICANTE
AND F.NOMBRE='Asus';

--8)
SELECT AVG(P.PRECIO)
FROM PRODUCTOS P, FABRICANTES F
WHERE F.ID = P.ID_FABRICANTE
AND F.NOMBRE='Asus';

--9)
SELECT MIN(P.PRECIO)
FROM PRODUCTOS P, FABRICANTES F
WHERE F.ID = P.ID_FABRICANTE
AND F.NOMBRE='Asus';

--10)
SELECT MAX(P.PRECIO)
FROM PRODUCTOS P, FABRICANTES F
WHERE F.ID = P.ID_FABRICANTE
AND F.NOMBRE='Asus';

--Parte de Pablo
--11)
SELECT SUM(PRECIO) 
FROM PRODUCTOS 
WHERE ID_FABRICANTE = (SELECT ID FROM FABRICANTES WHERE NOMBRE = 'Asus');

--12)
SELECT MAX(PRECIO), MIN(PRECIO), AVG(PRECIO), COUNT(*) 
FROM PRODUCTOS 
WHERE ID_FABRICANTE = (SELECT ID FROM FABRICANTES WHERE NOMBRE = 'Crucial');

--13)
SELECT F.NOMBRE, COUNT(P_ID) 
FROM FABRICANTES F 
LEFT JOIN PRODUCTOS;

--14)
SELECT F.NOMBRE, MAX(PRECIO), MIN(PRECIO), AVG(PRECIO) 
FROM FABRICANTES F, PRODUCTOS P 
WHERE F.ID = P.ID_FABRICANTE 
GROUP BY F.NOMBRE;

--15)
SELECT ID_FABRICANTE, MAX(PRECIO), MIN(PRECIO), AVG(PRECIO), COUNT(*) 
FROM PRODUCTOS 
GROUP BY ID_FABRICANTE 
HAVING AVG(PRECIO) > 200;

--16)
SELECT F.NOMBRE, MAX(PRECIO), MIN(PRECIO), AVG(PRECIO), COUNT(*) 
FROM FABRICANTES F, PRODUCTOS P 
WHERE F.ID = P.ID_FABRICANTE 
GROUP BY F.NOMBRE 
HAVING AVG(PRECIO) > 200;

--17)
SELECT COUNT(*) 
FROM PRODUCTOS 
WHERE PRECIO >= 180;

--18)
SELECT ID_FABRICANTE, COUNT(*) 
FROM PRODUCTOS 
WHERE PRECIO >= 180 
GROUP BY ID_FABRICANTE;

--19)
SELECT ID_FABRICANTE, AVG(PRECIO) FROM PRODUCTOS GROUP BY ID_FABRICANTE;

--20)
SELECT F.NOMBRE, AVG(PRECIO) 
FROM FABRICANTES F, PRODUCTOS P 
WHERE F.ID = P.ID_FABRICANTE 
GROUP BY F.NOMBRE;

--21)
SELECT F.NOMBRE 
FROM FABRICANTES F, PRODUCTOS P 
WHERE F.ID = P.ID_FABRICANTE 
GROUP BY F.NOMBRE 
HAVING AVG(PRECIO) >= 150;

--22)
SELECT F.NOMBRE 
FROM FABRICANTES F, PRODUCTOS P 
WHERE F.ID = P.ID_FABRICANTE 
GROUP BY F.NOMBRE 
HAVING COUNT(*) >= 2;