SET SERVEROUTPUT ON
--CURSORES EJERCIO 1--
DECLARE
    MATRICULA AUTOBUS.MATRICULA%TYPE;
    CURSOR AUTOBUSES IS
    SELECT MATRICULA
    FROM AUTOBUS;
BEGIN
    OPEN AUTOBUSES;
    
    LOOP
        FETCH AUTOBUSES INTO MATRICULA;
        EXIT WHEN AUTOBUSES%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Las matricula del autobus: ' || MATRICULA);
    END LOOP;
    
    CLOSE AUTOBUSES;
END;

--CURSORES EJERCICIO 2--
DECLARE
    CURSOR AUTOBUSES IS
    SELECT MATRICULA FROM AUTOBUS;
    
     rMatricula autobus.matricula%type;
BEGIN
    FOR rMatricula IN AUTOBUSES LOOP
        DBMS_OUTPUT.PUT_LINE('La matrícula del autobús: ' || rMatricula.matricula);
    END LOOP;
END;

--CURSORES EJERCICIO 3--
DECLARE
    CURSOR VIAJESPUBLICOS IS
        SELECT *
        FROM VIAJES
        WHERE TIPO = 'PUBLICO'
        FOR UPDATE OF TIPO;
BEGIN
    FOR VIAJES IN VIAJESPUBLICOS LOOP
        UPDATE VIAJES
        SET TIPO = 'PRIVADO'
        WHERE CURRENT OF VIAJESPUBLICOS;
    END LOOP;
END;

