--Consultas multitabla (Composición externa)<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

--A
SELECT F.NOMBRE, P.NOMBRE
FROM FABRICANTES F
LEFT JOIN PRODUCTOS P
ON F.ID = P.ID_FABRICANTE;

--B
SELECT F.NOMBRE, P.NOMBRE
FROM FABRICANTES F
LEFT JOIN PRODUCTOS P
ON F.ID = P.ID_FABRICANTE
WHERE P.NOMBRE IS NULL;

--C
-- No puede ser, ya que un producto siempre debe tener un fabricante pero
-- un fabricante puede no tener productos.

--Consultas resumen<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

--1)
SELECT COUNT (*)
FROM PRODUCTOS;

--2)
SELECT COUNT (ID)
FROM PRODUCTOS;

--3)
SELECT AVG(P.PRECIO)
FROM PRODUCTOS P;

--4)
SELECT MIN(P.PRECIO)
FROM PRODUCTOS P;

--5)
SELECT P.NOMBRE, P.PRECIO
FROM PRODUCTOS P
WHERE P.PRECIO = (SELECT MAX(PRECIO) FROM PRODUCTOS);

--6)
SELECT SUM(P.PRECIO)
FROM PRODUCTOS P;

--7)
SELECT COUNT (*)
FROM PRODUCTOS P, FABRICANTES F
WHERE F.ID = P.ID_FABRICANTE
AND F.NOMBRE='Asus';

--8)
SELECT AVG(P.PRECIO)
FROM PRODUCTOS P, FABRICANTES F
WHERE F.ID = P.ID_FABRICANTE
AND F.NOMBRE='Asus';

--9)
SELECT MIN(P.PRECIO)
FROM PRODUCTOS P, FABRICANTES F
WHERE F.ID = P.ID_FABRICANTE
AND F.NOMBRE='Asus';

--10)
SELECT MAX(P.PRECIO)
FROM PRODUCTOS P, FABRICANTES F
WHERE F.ID = P.ID_FABRICANTE
AND F.NOMBRE='Asus';